//! Antialiased bitmap type.
//!
//! `embedded-graphics`' own `MonoFont` stores one bit per pixel, which is what
//! makes a firmware look hand-cut: every glyph edge is either fully on or fully
//! off, so curves and diagonals step. The fonts LVGL renders - and therefore
//! the type on the reference firmware for this watch - carry four bits of
//! coverage per pixel instead, and that difference is most of what separates
//! the two on screen.
//!
//! This module is the same idea, kept inside embedded-graphics rather than
//! beside it: [`AaTextStyle`] implements the `TextRenderer` trait, which the
//! crate documents as its extension point for external renderers. `Text`,
//! alignment, and every `DrawTarget` keep working unchanged.
//!
//! Atlases are generated by `tools/generate-font.py` and committed, so a normal
//! build needs neither Python nor the source face.

mod jetbrains_mono_10x22;
mod jetbrains_mono_6x14;
mod jetbrains_mono_8x18;

use embedded_graphics::{
    draw_target::DrawTarget,
    geometry::{Point, Size},
    pixelcolor::{Rgb565, RgbColor},
    primitives::Rectangle,
    text::{
        Baseline,
        renderer::{TextMetrics, TextRenderer},
    },
};

pub use jetbrains_mono_6x14::JETBRAINS_MONO_6X14;
pub use jetbrains_mono_8x18::JETBRAINS_MONO_8X18;
pub use jetbrains_mono_10x22::JETBRAINS_MONO_10X22;

/// The firmware's UI face, in an ink colour over the surface it sits on.
///
/// Named rather than constructed at each call site for the same reason the
/// palette is: a later change of face is an edit here, not a sweep through
/// every screen.
#[must_use]
pub const fn ui_text(ink: Rgb565, background: Rgb565) -> AaTextStyle {
    AaTextStyle::new(&JETBRAINS_MONO_10X22, ink, background)
}

/// The same face at the size hints and secondary lines are set in.
#[must_use]
pub const fn hint_text(ink: Rgb565, background: Rgb565) -> AaTextStyle {
    AaTextStyle::new(&JETBRAINS_MONO_6X14, ink, background)
}

/// The size running prose is set in: a paragraph somebody actually reads.
///
/// The two sizes above are a UI face and a label face, and neither is a reading
/// size. A notification body in the label face fitted two hundred characters
/// into a screen that never carries more than a hundred, so it was small for no
/// gain; in the UI face it would not fit at all. This sits between them, which
/// is the only place a body of text belongs.
///
/// The third atlas costs 6,840 bytes of flash. That is the whole price, and it
/// is why this is the reading size rather than a fourth and a fifth: a size is
/// worth an atlas only when something is genuinely set in it.
#[must_use]
pub const fn body_text(ink: Rgb565, background: Rgb565) -> AaTextStyle {
    AaTextStyle::new(&JETBRAINS_MONO_8X18, ink, background)
}

/// Bits of coverage per pixel in every atlas this module reads.
const BPP: u32 = 4;
/// Distinct coverage levels one sample can express.
const LEVELS: usize = 1 << BPP;
/// Fully opaque coverage, and the divisor of the blend.
const OPAQUE: u8 = (1u8 << BPP) - 1;

/// A fixed-cell font whose glyphs carry partial coverage.
///
/// Monospace by construction: the cell width is the advance, which is why no
/// per-glyph metrics are stored and a character's position is a multiplication.
pub struct AaFont {
    /// Coverage samples, `BPP` bits each, row-major within a glyph and glyphs
    /// in character order.
    pub data: &'static [u8],
    pub cell: Size,
    /// Bytes per glyph row, padded to a whole byte.
    pub stride: u32,
    /// Distance from the top of the cell down to the baseline.
    pub baseline: u32,
    pub first: char,
    pub count: u32,
}

impl AaFont {
    /// Byte offset of a character's glyph, or `None` if the atlas lacks it.
    const fn glyph_offset(&self, character: char) -> Option<usize> {
        let first = self.first as u32;
        let code = character as u32;
        if code < first || code >= first + self.count {
            return None;
        }
        Some(((code - first) * self.stride * self.cell.height) as usize)
    }

    /// Coverage of one pixel within a glyph, `0..=OPAQUE`.
    fn coverage(&self, offset: usize, x: u32, y: u32) -> u8 {
        let per_byte = 8 / BPP;
        let index = offset + (y * self.stride + x / per_byte) as usize;
        let Some(byte) = self.data.get(index) else {
            return 0;
        };
        // Samples sit most significant bits first, so the leftmost pixel of a
        // byte needs the largest shift.
        let shift = (per_byte - 1 - x % per_byte) * BPP;
        (byte >> shift) & OPAQUE
    }
}

/// Blends 16 coverage levels between two colours once, so the per-pixel work
/// of a glyph is a table lookup rather than three divisions.
///
/// A glyph cell holds a few hundred pixels and this table holds sixteen
/// entries; building it per string is cheaper than blending even one row.
#[derive(Clone, Copy)]
struct Blend([Rgb565; LEVELS]);

impl Blend {
    fn new(text_color: Rgb565, background_color: Rgb565) -> Self {
        let mut table = [background_color; LEVELS];
        for (level, entry) in table.iter_mut().enumerate() {
            let level = u16::try_from(level).unwrap_or(0);
            let opaque = u16::from(OPAQUE);
            // Channels are five or six bits wide and the weights sum to
            // `OPAQUE`, so the quotient can never leave the range of the
            // channel it came from.
            let mix = |fore: u8, back: u8| -> u8 {
                let blended =
                    (u16::from(fore) * level + u16::from(back) * (opaque - level)) / opaque;
                u8::try_from(blended).unwrap_or(u8::MAX)
            };
            *entry = Rgb565::new(
                mix(text_color.r(), background_color.r()),
                mix(text_color.g(), background_color.g()),
                mix(text_color.b(), background_color.b()),
            );
        }
        Self(table)
    }

    fn get(&self, coverage: u8) -> Rgb565 {
        self.0[usize::from(coverage)]
    }
}

/// Draws text in an [`AaFont`], blending each glyph against a known background.
///
/// The background is part of the style rather than something the caller paints
/// first: the panel cannot be read back, so coverage has to be mixed against
/// the colour the text is known to sit on. Painting the whole cell also means a
/// redrawn value overwrites the one before it without a clearing pass, which is
/// what keeps a ticking clock from flashing.
#[derive(Clone, Copy)]
pub struct AaTextStyle {
    pub font: &'static AaFont,
    pub text_color: Rgb565,
    pub background_color: Rgb565,
}

impl AaTextStyle {
    #[must_use]
    pub const fn new(font: &'static AaFont, text_color: Rgb565, background_color: Rgb565) -> Self {
        Self {
            font,
            text_color,
            background_color,
        }
    }

    /// Top edge of the cell for a baseline the caller asked for.
    const fn top_of_cell(&self, position: Point, baseline: Baseline) -> i32 {
        let height = self.font.cell.height.cast_signed();
        match baseline {
            Baseline::Top => position.y,
            Baseline::Bottom => position.y - height,
            Baseline::Middle => position.y - height / 2,
            Baseline::Alphabetic => position.y - self.font.baseline.cast_signed(),
        }
    }

    /// Advance of one character, which for a monospace cell is its width.
    const fn advance(&self) -> i32 {
        self.font.cell.width.cast_signed()
    }
}

impl TextRenderer for AaTextStyle {
    type Color = Rgb565;

    fn draw_string<D>(
        &self,
        text: &str,
        position: Point,
        baseline: Baseline,
        target: &mut D,
    ) -> Result<Point, D::Error>
    where
        D: DrawTarget<Color = Self::Color>,
    {
        let blend = Blend::new(self.text_color, self.background_color);
        let top = self.top_of_cell(position, baseline);
        let font = self.font;

        let characters = i32::try_from(text.chars().count()).unwrap_or(0);
        let width = characters.saturating_mul(self.advance());
        let next = Point::new(position.x.saturating_add(width), position.y);
        if width <= 0 {
            return Ok(next);
        }

        // One rectangle for the whole run, not one per character. A display
        // driver turns each of these into an address window - two commands with
        // four bytes of argument, plus the memory-write that follows - so a
        // per-glyph rectangle spent that addressing 32 times on a line of 32
        // characters, for pixels that are contiguous on the panel anyway. The
        // terminal face is around 130 cells, which was around 900 SPI
        // transactions where a few dozen carry the same picture.
        //
        // What makes one rectangle correct is the order below: `fill_contiguous`
        // is documented to consume colours row by row across the area, so the
        // outer loop walks the rows of the cell and the inner one hands each
        // character its slice of that row before moving down.
        // Rows the target would throw away are not produced at all.
        //
        // A target clips what it is handed, but `fill_contiguous` takes its
        // colours in order, so a row above the clip still has to come out of the
        // iterator before the first kept one does - and pulling a glyph pixel is
        // the expensive part. `UiScratch` advances past them with `nth`, which
        // runs the coverage lookup and the blend for every one and then drops
        // the result.
        //
        // It is composing that pays for this. A transition builds the panel in
        // twelve-pixel stripes and the UI face is twenty-two tall, so a run
        // straddling a boundary was rasterised whole for each stripe it touched
        // - the second pass computing a stripe's worth of pixels purely to reach
        // the ones it wanted. On a full panel the clip is the panel and nothing
        // here changes.
        let clip = target.bounding_box();
        let clip_top = clip.top_left.y;
        let clip_bottom = clip_top.saturating_add(i32::try_from(clip.size.height).unwrap_or(0));
        let cell_height = i32::try_from(font.cell.height).unwrap_or(0);
        let first_visible = top.max(clip_top);
        let past_visible = top.saturating_add(cell_height).min(clip_bottom);
        if past_visible <= first_visible {
            return Ok(next);
        }
        let first_row = u32::try_from(first_visible - top).unwrap_or(0);
        let visible_rows = u32::try_from(past_visible - first_visible).unwrap_or(0);

        let area = Rectangle::new(
            Point::new(position.x, first_visible),
            Size::new(u32::try_from(width).unwrap_or(0), visible_rows),
        );
        let colors = (first_row..first_row + visible_rows).flat_map(move |row| {
            text.chars().flat_map(move |character| {
                // An unmapped character leaves its cell in the background colour
                // rather than a substitute glyph: the atlas covers the printable
                // range, and anything outside it is a bug worth seeing as a gap.
                let offset = font.glyph_offset(character);
                (0..font.cell.width).map(move |column| {
                    let coverage = offset.map_or(0, |offset| font.coverage(offset, column, row));
                    blend.get(coverage)
                })
            })
        });
        target.fill_contiguous(&area, colors)?;

        Ok(next)
    }

    fn draw_whitespace<D>(
        &self,
        width: u32,
        position: Point,
        baseline: Baseline,
        target: &mut D,
    ) -> Result<Point, D::Error>
    where
        D: DrawTarget<Color = Self::Color>,
    {
        if width > 0 {
            let top = self.top_of_cell(position, baseline);
            target.fill_solid(
                &Rectangle::new(
                    Point::new(position.x, top),
                    Size::new(width, self.font.cell.height),
                ),
                self.background_color,
            )?;
        }
        Ok(Point::new(
            position.x + i32::try_from(width).unwrap_or(0),
            position.y,
        ))
    }

    fn measure_string(&self, text: &str, position: Point, baseline: Baseline) -> TextMetrics {
        let characters = i32::try_from(text.chars().count()).unwrap_or(i32::MAX);
        let width = characters.saturating_mul(self.advance());
        let top = self.top_of_cell(position, baseline);
        TextMetrics {
            bounding_box: Rectangle::new(
                Point::new(position.x, top),
                Size::new(u32::try_from(width).unwrap_or(0), self.font.cell.height),
            ),
            next_position: Point::new(position.x + width, position.y),
        }
    }

    fn line_height(&self) -> u32 {
        self.font.cell.height
    }
}

#[cfg(test)]
mod tests {
    use embedded_graphics::{
        geometry::{Point, Size},
        primitives::Rectangle,
        text::{Baseline, renderer::TextRenderer},
    };

    use super::ui_text;
    use crate::{canvas::Canvas, probe::Probe, theme};

    /// One stripe of the transition scratch: the panel's width, twelve tall.
    const STRIPE: Rectangle = Rectangle::new(Point::new(0, 0), Size::new(240, 12));

    /// A run drawn against a stripe paints that stripe exactly as a run against
    /// the whole panel does, and rasterises nothing below it.
    ///
    /// The saving and the risk are the same edit. The UI face is twenty-two
    /// pixels tall against a twelve-pixel stripe, so a run at the top of one
    /// covers ten rows the stripe never keeps; producing them anyway costs a
    /// coverage lookup and a blend each, and producing the wrong ones shears the
    /// text. The first assertion is that the picture did not move. The second is
    /// that the work was actually skipped rather than left to the target.
    #[test]
    fn a_clipped_run_paints_exactly_what_an_unclipped_one_does() {
        let style = ui_text(theme::TEXT, theme::SURFACE);
        let at = Point::new(10, 0);

        let mut whole = Probe::new();
        let _ = style.draw_string("HELLO", at, Baseline::Top, &mut Canvas::new(&mut whole));

        let mut stripe = Probe::clipped_to(STRIPE);
        let _ = style.draw_string("HELLO", at, Baseline::Top, &mut Canvas::new(&mut stripe));

        for y in 0..12 {
            for x in 0..240 {
                let point = Point::new(x, y);
                assert_eq!(stripe.pixel(point), whole.pixel(point), "at {point:?}");
            }
        }
        assert!(
            stripe.out_of_bounds().is_empty(),
            "rows outside the stripe were rasterised anyway: {:?}",
            stripe.out_of_bounds()
        );
    }

    /// A run entirely above or below the stripe draws nothing at all.
    #[test]
    fn a_run_outside_the_stripe_produces_no_pixels() {
        let style = ui_text(theme::TEXT, theme::SURFACE);
        let mut stripe = Probe::clipped_to(STRIPE);
        let _ = style.draw_string(
            "HELLO",
            Point::new(10, 40),
            Baseline::Top,
            &mut Canvas::new(&mut stripe),
        );
        assert!(!stripe.painted_within(Rectangle::new(Point::zero(), Size::new(240, 240))));
    }
}
