#!/usr/bin/env python3
"""Rasterises a TrueType face into an antialiased bitmap font for the firmware.

The firmware cannot carry a TrueType rasteriser, so glyphs are baked here into
a fixed-cell coverage atlas and emitted as a Rust constant. Running this is a
deliberate, occasional act: the generated file is committed, so a normal build
needs neither Python nor the font.

Coverage is stored at a configurable depth. Four bits per pixel is the default
because it is what antialiased type needs to stop looking hand-cut, and it is
what LVGL uses for the same reason; two bits halves the data and still beats a
one-bit font by a wide margin, should flash get tight.

Only a contiguous character range is supported. A monospace UI font wants the
printable ASCII block, and a clock face wants digits and a colon, which happen
to be contiguous too - a sparse mapping would cost a lookup table in flash and
buy nothing.

Example:
    tools/generate-font.py \
        --font third_party/liberation-mono/LiberationMono-Bold.ttf \
        --em 20 --cell 12x27 --bpp 4 \
        --name LIBERATION_MONO_12X27 \
        --out src/ui/font/liberation_mono_12x27.rs
"""

import argparse
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont


def parse_cell(value: str) -> tuple[int, int]:
    width, _, height = value.partition("x")
    return int(width), int(height)


def render_glyph(font, char: str, cell: tuple[int, int], baseline: int) -> Image.Image:
    """Draws one character into its cell, positioned on the shared baseline.

    Every glyph is drawn at the same origin rather than at its own ink box, so
    the firmware can index the atlas by character alone and never has to store
    per-glyph offsets.
    """
    width, height = cell
    image = Image.new("L", (width, height), 0)
    # PIL's "ls" anchor places the origin on the baseline at the left edge,
    # which is exactly the reference the firmware renderer draws from.
    ImageDraw.Draw(image).text((0, baseline), char, font=font, fill=255, anchor="ls")
    return image


def pack(image: Image.Image, bpp: int) -> bytes:
    """Packs one glyph's coverage, most significant bits leftmost.

    Rows are padded to whole bytes so a row can be addressed by multiplication
    rather than by carrying a bit offset across the glyph.
    """
    per_byte = 8 // bpp
    levels = (1 << bpp) - 1
    packed = bytearray()
    for y in range(image.height):
        byte = 0
        filled = 0
        for x in range(image.width):
            # Round to nearest level rather than truncating: truncation biases
            # every edge one step lighter and visibly thins the stems.
            sample = (image.getpixel((x, y)) * levels + 127) // 255
            byte = (byte << bpp) | sample
            filled += 1
            if filled == per_byte:
                packed.append(byte)
                byte = 0
                filled = 0
        if filled:
            packed.append(byte << (bpp * (per_byte - filled)))
    return bytes(packed)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=pathlib.Path)
    parser.add_argument("--em", required=True, type=int, help="nominal pixel size")
    parser.add_argument("--cell", required=True, type=parse_cell, help="WxH")
    parser.add_argument("--bpp", type=int, default=4, choices=(1, 2, 4))
    parser.add_argument("--first", type=lambda v: int(v, 0), default=0x20)
    parser.add_argument("--count", type=int, default=95)
    parser.add_argument("--baseline", type=int, default=None)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    font = ImageFont.truetype(str(args.font), args.em)
    ascent, _ = font.getmetrics()
    baseline = args.baseline if args.baseline is not None else ascent
    width, height = args.cell
    advance = round(font.getlength("0"))

    if advance != width:
        print(
            f"warning: cell width {width} does not match the face's advance "
            f"{advance} at em={args.em}; glyphs will not be evenly spaced",
            file=sys.stderr,
        )

    data = bytearray()
    for index in range(args.count):
        glyph = render_glyph(font, chr(args.first + index), args.cell, baseline)
        data.extend(pack(glyph, args.bpp))

    stride = (width * args.bpp + 7) // 8
    rows = [
        ", ".join(f"0x{b:02x}" for b in data[offset : offset + 16])
        for offset in range(0, len(data), 16)
    ]
    body = "\n".join(f"    {row}," for row in rows)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        f"""//! Generated by `tools/generate-font.py`. Do not edit.
//!
//! Source: {args.font.name}, em {args.em}, {args.bpp} bits of coverage per pixel.
//! Characters U+{args.first:04X}..=U+{args.first + args.count - 1:04X}.

use embedded_graphics::geometry::Size;

use super::AaFont;

pub const {args.name}: AaFont = AaFont {{
    data: &{args.name}_DATA,
    cell: Size::new({width}, {height}),
    stride: {stride},
    baseline: {baseline},
    first: '\\u{{{args.first:x}}}',
    count: {args.count},
}};

static {args.name}_DATA: [u8; {len(data)}] = [
{body}
];
"""
    )
    print(
        f"{args.out}: {args.count} glyphs, {width}x{height} cell, "
        f"{args.bpp} bpp, {len(data)} bytes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
